[package]
name = "msh"
version = "0.1.0"
authors = ["Justin Mayhew <mayhew@live.ca>"]
edition = "2018"

[dependencies]
atty = "0.2"
env_logger = "0.6"
failure = "0.1"
getopts = "0.2"
libc = "0.2"
log = "0.4"
nix = "0.12"
